[package]
name = "whitelist"

[workspace]
members = ["program"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"

[programs.localnet]
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"

[scripts]
test = "yarn run mocha -t 1000000 tests/"