anchor_version = "0.20.1"
solana_version = "1.9.17"

[workspace]
members = [
  "identity-verification/program",
  "governance/program"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
spl_governance = "8RSMYUyLkSQ9Vj64SVBqDEugzBpzphyPAGDvZ6VySHgP"
identity_verification = "idVN1nN6rUorVnUweTxDEM71GsxYjF4d9XbuX8Xfm21"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./identity-verification/tests/**/*.ts"
