anchor_version = "0.20.1"
solana_version = "1.9.17"

[workspace]
members = [
  "governance/program",
  "token-lending/program",
  "whitelist/program"
]

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
spl_governance = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
