anchor_version = "0.20.1"
solana_version = "1.9.17"

[workspace]
members = [
  "whitelist/program"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
spl_governance = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"

[programs.devnet]
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"

[programs.localnet]
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"

[scripts]
test = "yarn run mocha -t 1000000 whitelist/tests"