anchor_version = "0.20.1"
solana_version = "1.9.17"

[workspace]
members = [
  "whitelist/program",
  "governance/program"
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
spl_governance = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"

[programs.devnet]
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"
spl_governance = "7cjMfQWdJ9Va2pjSZM3D9G2PGCwgWMzbgcaVymCtRVQZ"

[programs.localnet]
whitelist = "JDS6WitBF654whkcWz5i5HX1ixska8Je4ahw7XYS7h5A"
spl_governance = "7cjMfQWdJ9Va2pjSZM3D9G2PGCwgWMzbgcaVymCtRVQZ"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./whitelist/tests/**/*.ts"
