[workspace]
members = [
    "programs/governance/program",
    "programs/identity-verification/program",
    "programs/permissioned-list/program"
]

exclude = [
]

[profile.dev]
split-debuginfo = "unpacked"
