[workspace]
members = [
    "governance/addin-mock/program",
    "governance/addin-api",
    "governance/program",
    "governance/test-sdk",
    "governance/tools",
    "governance/chat/program",
    "identity-verification/program",
]

exclude = []

[profile.dev]
split-debuginfo = "unpacked"
