[package]
name = "identity_verification"

[workspace]
members = ["program"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/"